### ISSUE TITLE
Windows running issues

### ISSUE THREAD

**Issue by lufoleos** [looCiprian/GC2-sheet#10]
After compiling into a Windows executable program, it can only be run in Cmd. Double click on the run prompt, "This is a command line tool. You need to open cmd.exe and run it from there
![260196198-e48e6578-f1fd-4706-b58b-6e6f3a6a1f5c](https://github.com/looCiprian/GC2-sheet/assets/142131571/ad9e355a-1a08-4405-8faa-ed2cf6261b3f)

**Comment by lufoleos** [comment]
"Hello, in a Windows environment, when running GC2-sheet, how can I modify it to run silently after double-clicking the executable program? Also, I have another question: currently, when running the GC2-sheet program on a Windows system and executing commands in Google Sheets, there's a brief flicker of a black box each time. How can I resolve this issue? Looking forward to your response.

**Comment by elbae** [comment]
@lufoleos how do you build the .exe?

**Comment by elbae** [comment]
```bash
env GOOS=windows GOARCH=386 go build -buildmode=pie -ldflags -H=windowsgui gc2-sheet.go
```
---
This build mode is for your first problem, but maybe you can have better results with 
```bash
env GOOS=windows GOARCH=386 go build gc2-sheet.g
```
and then 
```cmd
powershell -exec bypass "Start-Process -FilePath \"c:\users\dev\downloads\gc2-sheet.exe\" -WindowStyle Hidden"
```

**Comment by lufoleos** [comment]
@elbae 

1. The initial build was constructed in this way, and when the .exe built using this method is double-clicked to run, it prompts: "This is a command line tool. You need to open cmd.exe and run it from there."
```
export CGO_ENABLED=0 GOOS=windows GOARCH=amd64
go build gc2-sheet.go
```

2. When finally built using this approach, the .exe, upon double-clicking, exits immediately or crashes, and it still requires running via cmd instead.
```
export CGO_ENABLED=0 GOOS=windows GOARCH=amd64
go build -ldflags -H=windowsgui gc2-sheet.go
```

**Comment by matthewneeley** [comment]
Under cmd\root.go in func init() add the line: cobra.MousetrapHelpText = "" to the top of the init function and then you can compile with:
go build -o test.exe -ldflags "-s -w -H windowsgui" gc2-sheet.go
