### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hitchhiker139** [looCiprian/GC2-sheet#11]
Anyone else seeing the runtime error? If so, how did you fix it?

**Comment by looCiprian** [comment]
Please provide some information about your system and the error stack trace. You can run the tool using verbose mode as described here https://github.com/looCiprian/GC2-sheet#troubleshooting

**Comment by hitchhiker139** [comment]
Here is what i am gettting: 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8a75de]

goroutine 1 [running]:
GC2-sheet/internal/C2.createSheet(0x0, 0xc0001388a0)
	/opt/GC2-sheet/internal/C2/create.go:30 +0x19e
GC2-sheet/internal/C2.Run()
	/opt/GC2-sheet/internal/C2/c2.go:41 +0x2b0
GC2-sheet/cmd.glob..func1(0xebace0?, {0xa529ea?, 0x6?, 0x6?})
	/opt/GC2-sheet/cmd/root.go:53 +0x2c5
github.com/spf13/cobra.(*Command).execute(0xebace0, {0xc00013a010, 0x6, 0x6})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xebace0)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
GC2-sheet/cmd.Execute()
	/opt/GC2-sheet/cmd/root.go:70 +0x25
main.main()

**Comment by looCiprian** [comment]
Did you follow the configuration steps described [here](https://github.com/looCiprian/GC2-sheet#set-up)?
The issues could be related to:
- Google APIs are not enabled (Step 2)
- Google sheet is not shared with the service account (Step 3)

**Comment by hitchhiker139** [comment]
I followed all the steps and double checked both APIs, google sheets (shared with the service account) and drive share settings.

**Comment by looCiprian** [comment]
I've pushed a small change, it may help you to identify the issue. The issue is related to your configuration and not the tool itself.
