### ISSUE TITLE
Failed to pull new command and ticker

### ISSUE THREAD

**Issue by robwillisinfo** [looCiprian/GC2-sheet#16]
Followed the instructions on the Readme, created the service account, enabled the apis, shared everything out with the service account as editor, but after compiling and then executing I receive the following error:

$ ./GC2-sheet         
2024/10/04 12:14:58 Using configuration file
2024/10/04 12:15:08 [-] Failed to pull new command and ticker: an error occurred while pulling command and ticker from remote source: %!w(nil)
2024/10/04 12:15:18 [-] Failed to pull new command and ticker: an error occurred while pulling command and ticker from remote source: %!w(nil)
2024/10/04 12:15:28 [-] Failed to pull new command and ticker: an error occurred while pulling command and ticker from remote source: %!w(nil)

I even tried rerunning through all of the steps with a new share and sheet, but still getting the same error.

**Comment by robwillisinfo** [comment]
It looks like this error was related to not escaping the \n's in the private key.

**Comment by CircuitSoul** [comment]
@robwillisinfo the JSON key file generated by Google already escapes \n.

> junk account
![Image](https://github.com/user-attachments/assets/20ae02c7-8d54-4b0f-9517-8746790e2f3a)

Did you need to add more escapes?
