### ISSUE TITLE
issue in root.go file

### ISSUE THREAD

**Issue by machine1337** [looCiprian/GC2-sheet#4]
Hello plz check the following screenshot when i uncommenting the configuration.SetOptions(<json>,<sheetId>,<driveId>)...i am getting error "expected operand, found <"...plz check the screenshot also
![as](https://user-images.githubusercontent.com/82051128/184466960-6cfefed5-a005-4368-b2b0-f150afc60208.png)

**Comment by looCiprian** [comment]
Hi!
Line 26 is used to hardcode the _json file_, _sheetId_ and _driveID_, so you have to substitute `<json>, <sheetId>, <driveId>` with your values

**Comment by machine1337** [comment]
@looCiprian Hello I have configured everything correctly but still getting same error....is there any way to contact with you?

**Comment by looCiprian** [comment]
Hi,

you should write something like this:

`configuration.SetOptions("yourJsonFileExcaped", "1234", "4321")`

Please substitute:

1. 1234 with your sheetId
2. 4321 with your driveId
3. yourJsonFileExcaped with your json file escaped (you can read [here](https://www.freeformatter.com/json-escape.html) how to escape json string)

**Comment by machine1337** [comment]
@looCiprian  ok got it...but is it possible to rewrite it in C# or Python?

**Comment by looCiprian** [comment]
Hi, unfortunately, no because I've chosen GoLang since it is a little bit harder to reverse it than C# and Python. But if you want you can try it yourself 😁

**Comment by machine1337** [comment]
@looCiprian changing directory is not working in windows.....when i type cd /d E:\ then it shows exit status 1 and when i  again type dir then it is still in that directory from where payload is executed?
