### ISSUE TITLE
 BUG appears when I perform the last step，Is there a problem with the source code ？

### ISSUE THREAD

**Issue by Ron-zs** [looCiprian/GC2-sheet#5]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0xd9640d]

goroutine 39 [running]:
GC2-sheet/internal/C2.readSheet(0xc000151ad0, 0xc000108600)
        D:/1REDTOOLS/C2/GC2-sheet/internal/C2/read.go:31 +0x1ed
GC2-sheet/internal/C2.Run.func1()
        D:/1REDTOOLS/C2/GC2-sheet/internal/C2/c2.go:70 +0xa6
created by GC2-sheet/internal/C2.Run
        D:/1REDTOOLS/C2/GC2-sheet/internal/C2/c2.go:59 +0x267

**Comment by looCiprian** [comment]
Hi, what do you mean by "_last step_"?
Can you provide some information regarding your environment, please? Like OS type, Go version, steps to reproduce, ...
Thanks

**Comment by arishwani** [comment]
I have the same issue, was this resolved?

**Comment by looCiprian** [comment]
The issue has not been resolved since no further data was provided. You are probably using a wrong sheet ID
