### ISSUE TITLE
IoCs and Yara Rules

### ISSUE THREAD

**Issue by mttaggart** [looCiprian/GC2-sheet#6]
Hey! You have a project here that can be used both by legitimate offensive operators and criminals. In fact, they are: https://www.bleepingcomputer.com/news/security/hackers-abuse-google-command-and-control-red-team-tool-in-attacks/

A responsible thing to do is to generate Yara Rules/IoCs for your tool so defenders can detect this in their environment. You've requested that the tool not be uploaded to VirusTotal, which isn't a great move. But at the very least, you could provide detection rules, if this is in fact for legitimate testing purposes.

**Comment by looCiprian** [comment]
Hi, thank you for your message.
The tool was already submitted to VirusTotal but both the behavior analysis nor the static analysis didn't detect any malicious behavior.

Yara Rules are on the way.
