### ISSUE TITLE
Issues with runtime 

### ISSUE THREAD

**Issue by arishwani** [looCiprian/GC2-sheet#8]
Hi, I came across this issue while using kali box. 

This is my go version.

go version go1.19.6 linux/amd64

The issue: 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8bc4cd]

 

goroutine 53 [running]:
GC2-sheet/internal/C2.readSheet(0xc0001cb7d0, 0xc0001327e0)
        GC2-sheet/internal/C2/read.go:31 +0x1ed
GC2-sheet/internal/C2.Run.func1()
       GC2-sheet/internal/C2/c2.go:70 +0xa6
created by GC2-sheet/internal/C2.Run
       GC2-sheet/internal/C2/c2.go:59 +0x267

Thanks 
Ari

**Comment by looCiprian** [comment]
Same of #5

**Comment by arishwani** [comment]
Hi Lorenzo,

Thank you for getting back to me. The sheet id is correct and double checked with a different sheet id still the same issue. The command I ran is 

gc2-sheet --key "json file" --sheet "sheet id" --drive "drive id" 

Was not lucky to get it to work. Also, if you have more documentation to share I would appreciate it.

**Comment by looCiprian** [comment]
I've just tested it and it works. Be sure to read the README.md file carefully and try again.

**Comment by arishwani** [comment]
Thank you, there was an issue with API key associate with the service account and was able to fix it. This issue can be closed. 
Regards,.
